<script lang="ts">
  import { toPng } from "html-to-image";

  import Render from "./Render.svelte";

  async function handleDownload() {
    const element = document.getElementById("chart")!;

    const dataUrl = await toPng(element);
    // Download
    const link = document.createElement("a");
    link.download = "chart.png";
    link.href = dataUrl;
    link.click();
  }
</script>

<div>
  <h1 class="font-bold text-3xl">Chunithm Scraper</h1>

  <Render
    input={{
      profile: {
        characterRarity: "RAINBOW",
        characterImage: "/api/profileImg?img=a48871f78a3f1e9d.png",
        teamEmblem: "NORMAL",
        teamName: "ＣＰ　ｖｓ　ＣＥＤＴ",
        honorLevel: "PLATINUM",
        honorText: "携帯恋話",
        playerLevel: 70,
        playerName: "Ｌｅｏψｒθφ",
        classEmblem: 4,
        rating: 16.29,
        overpowerValue: 28475.22,
        overpowerPercent: 26.62,
        lastPlayed: new Date("2025-04-04T07:49:00.000Z"),
        playCount: 465,
      },
      best: [
        {
          id: 749,
          title: "Fracture Ray",
          difficulty: "master",
          score: 1008159,
          clearMark: "HARD",
          fc: true,
          aj: false,
        },
        {
          id: 697,
          title: "folern",
          difficulty: "master",
          score: 1007850,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2562,
          title: "Prominence",
          difficulty: "master",
          score: 1008663,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2582,
          title: "Ultimate Force",
          difficulty: "expert",
          score: 1007412,
          clearMark: "HARD",
          fc: true,
          aj: false,
        },
        {
          id: 695,
          title: "ハートアタック",
          difficulty: "master",
          score: 1008153,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 1086,
          title: "祈 -我ら神祖と共に歩む者なり-",
          difficulty: "expert",
          score: 1007155,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2339,
          title: "Daphnis",
          difficulty: "expert",
          score: 1007602,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2739,
          title: "Aether Crest: Celestial",
          difficulty: "expert",
          score: 1007554,
          clearMark: "BRAVE",
          fc: false,
          aj: false,
        },
        {
          id: 2241,
          title: "DA'AT -The First Seeker of Souls-",
          difficulty: "expert",
          score: 1008328,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2648,
          title: "Tuatha Dé Danann",
          difficulty: "expert",
          score: 1008399,
          clearMark: "HARD",
          fc: true,
          aj: false,
        },
        {
          id: 2135,
          title: "IMPACT",
          difficulty: "master",
          score: 1006889,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 994,
          title: "Last Celebration",
          difficulty: "master",
          score: 1005722,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 1086,
          title: "祈 -我ら神祖と共に歩む者なり-",
          difficulty: "master",
          score: 997538,
          clearMark: "CLEAR",
          fc: false,
          aj: false,
        },
        {
          id: 2652,
          title: "Forsaken Tale",
          difficulty: "expert",
          score: 1006530,
          clearMark: "BRAVE",
          fc: false,
          aj: false,
        },
        {
          id: 784,
          title: "YURUSHITE",
          difficulty: "master",
          score: 1003890,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2658,
          title: "熱異常",
          difficulty: "master",
          score: 1008341,
          clearMark: "HARD",
          fc: true,
          aj: false,
        },
        {
          id: 2397,
          title: "もぺもぺ",
          difficulty: "master",
          score: 1008345,
          clearMark: "HARD",
          fc: true,
          aj: false,
        },
        {
          id: 2648,
          title: "Tuatha Dé Danann",
          difficulty: "master",
          score: 999420,
          clearMark: "CLEAR",
          fc: false,
          aj: false,
        },
        {
          id: 2428,
          title: "とあちゃんのおもちゃ箱",
          difficulty: "master",
          score: 1004754,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2354,
          title: "月の光",
          difficulty: "master",
          score: 1005393,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2634,
          title: "Dramatic…?",
          difficulty: "master",
          score: 1008267,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 999,
          title: "AttraqtiA",
          difficulty: "master",
          score: 1004293,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2339,
          title: "Daphnis",
          difficulty: "master",
          score: 995496,
          clearMark: "CLEAR",
          fc: false,
          aj: false,
        },
        {
          id: 2064,
          title: "ピュグマリオンの咒文",
          difficulty: "master",
          score: 1008611,
          clearMark: "BRAVE",
          fc: true,
          aj: false,
        },
        {
          id: 998,
          title: "Arcahv",
          difficulty: "master",
          score: 1008485,
          clearMark: "BRAVE",
          fc: true,
          aj: false,
        },
        {
          id: 2340,
          title: "To：Be Continued",
          difficulty: "master",
          score: 999604,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2127,
          title: "プナイプナイたいそう",
          difficulty: "master",
          score: 1006433,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 1106,
          title: "アポカリプスに反逆の焔を焚べろ",
          difficulty: "master",
          score: 1002790,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 1107,
          title: "AstrøNotes.",
          difficulty: "master",
          score: 1003742,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2193,
          title: "モ°ルモ°ル",
          difficulty: "master",
          score: 1008287,
          clearMark: "BRAVE",
          fc: false,
          aj: false,
        },
      ],
      new: [
        {
          id: 2562,
          title: "Prominence",
          difficulty: "master",
          score: 1008663,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2652,
          title: "Forsaken Tale",
          difficulty: "expert",
          score: 1006530,
          clearMark: "BRAVE",
          fc: false,
          aj: false,
        },
        {
          id: 2634,
          title: "Dramatic…?",
          difficulty: "master",
          score: 1008267,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2739,
          title: "Aether Crest: Celestial",
          difficulty: "expert",
          score: 1007554,
          clearMark: "BRAVE",
          fc: false,
          aj: false,
        },
        {
          id: 2648,
          title: "Tuatha Dé Danann",
          difficulty: "master",
          score: 999420,
          clearMark: "CLEAR",
          fc: false,
          aj: false,
        },
        {
          id: 1086,
          title: "祈 -我ら神祖と共に歩む者なり-",
          difficulty: "master",
          score: 997538,
          clearMark: "CLEAR",
          fc: false,
          aj: false,
        },
        {
          id: 1086,
          title: "祈 -我ら神祖と共に歩む者なり-",
          difficulty: "expert",
          score: 1007155,
          clearMark: "HARD",
          fc: false,
          aj: false,
        },
        {
          id: 2652,
          title: "Forsaken Tale",
          difficulty: "master",
          score: 990270,
          clearMark: "CLEAR",
          fc: false,
          aj: false,
        },
        {
          id: 2648,
          title: "Tuatha Dé Danann",
          difficulty: "master",
          score: 999420,
          clearMark: "CLEAR",
          fc: false,
          aj: false,
        },
        {
          id: 2339,
          title: "Daphnis",
          difficulty: "master",
          score: 995496,
          clearMark: "CLEAR",
          fc: false,
          aj: false,
        },
      ],
    }}
  />

  <button onclick={handleDownload}>Download</button>
</div>
