import { Img, OffthreadVideo, staticFile } from "remotion";
import {
  AbsoluteFill,
  interpolate,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";

import {
  backgroundMapping,
  logoMapping,
} from "../../chuni-web/src/lib/constants/pureMapping";

import { FC } from "react";
import { z } from "zod";
import { cn } from "@repo/ui/utils";
import { difficultyColorMap, getLamp, getRank } from "@repo/core/chuni";
import { recordViewSchema } from "./types";

type RecordViewProps = z.infer<typeof recordViewSchema> & {
  generatorVersion?: string;
};

const getWeightedLength = (text: string): number => {
  let weight = 0;
  for (const char of text) {
    const code = char.charCodeAt(0);
    // Japanese characters (Hiragana, Katakana, Kanji, Full-width)
    // U+3000-U+30FF: Japanese punctuation, Hiragana, Katakana
    // U+4E00-U+9FFF: CJK Unified Ideographs (Kanji)
    // U+FF00-U+FFEF: Full-width characters
    if (
      (code >= 0x3000 && code <= 0x30ff) ||
      (code >= 0x4e00 && code <= 0x9fff) ||
      (code >= 0xff00 && code <= 0xffef)
    ) {
      weight += 1.8; // Japanese characters take more space
    } else {
      weight += 1; // Roman characters
    }
  }
  return weight;
};

const getResponsiveFontSize = (text: string): string => {
  const weightedLength = getWeightedLength(text);

  // Smooth transition based on weighted text length
  if (weightedLength <= 20) return "text-5xl";
  if (weightedLength <= 30) return "text-4xl";
  return "text-3xl";
};

export const RecordView: FC<RecordViewProps> = ({
  version,
  chart,
  video,
  detail,
  generatorVersion = "dev",
}) => {
  const frame = useCurrentFrame();
  const { durationInFrames } = useVideoConfig();

  // Fade in and out
  const opacity = interpolate(
    frame,
    [0, 30, durationInFrames - 30, durationInFrames],
    [0, 1, 1, 0],
  );

  const backgroundImg = staticFile(
    "chuni-web" + backgroundMapping[version as keyof typeof backgroundMapping],
  );
  const versionLogo = staticFile(
    "chuni-web" + logoMapping[version as keyof typeof logoMapping],
  );
  const videoUrl = staticFile("files/" + video.url);

  const lamp = getLamp(chart.score, chart.fc, chart.aj);

  // Dynamic font sizes for title and artist
  const titleFontSize = getResponsiveFontSize(chart.title);
  const artistFontSize = getResponsiveFontSize(chart.artist);

  // A <AbsoluteFill> is just a absolutely positioned <div>!
  return (
    <AbsoluteFill>
      <AbsoluteFill>
        <Img src={backgroundImg} className="w-full" />
      </AbsoluteFill>
      <AbsoluteFill
        className="bg-cover bg-center bg-no-repeat flex flex-row gap-8 p-8"
        style={{ opacity }}
      >
        <aside className="flex flex-col gap-8 flex-2/3">
          <OffthreadVideo
            src={videoUrl}
            volume={opacity * video.volumeMultiplier}
            trimBefore={video.offset * 60}
          />

          <div className="bg-white/40 p-4 flex-1 flex flex-col justify-between items-start">
            <p className="text-6xl p-12">{detail.comment}</p>

            <p className="text-gray-500 text-2xl">
              Generated by github.com/leomtors/chuumai-tools | Video Generator
              Version {generatorVersion}
            </p>
          </div>
        </aside>

        <main className="flex flex-col gap-8 flex-1/3">
          <header className="flex justify-between bg-white/40">
            <div className="font-bold text-5xl flex flex-col gap-2 justify-evenly pl-8 py-8">
              <p>Rating #{detail.rankTotal}</p>
              <p className="text-4xl">
                {detail.rankType} #{detail.rankInType}
              </p>
            </div>

            <Img src={versionLogo} className="h-48 self-end" />
          </header>

          <article
            className={cn(
              "p-8 flex-1 flex flex-col gap-8",
              difficultyColorMap[chart.difficulty],
            )}
          >
            <section className="flex gap-8">
              <Img
                className="flex-3/5"
                src={`https://s3.lmhome.dev/chunithm/musicImages/${chart.image}`}
              />

              <div className="flex flex-col gap-8 flex-2/5">
                <p className="font-bold text-5xl text-center">
                  {chart.difficulty.toUpperCase()}
                </p>

                <div className="bg-white p-2 flex-1 flex flex-col gap-2 font-helvetica">
                  <p className="text-4xl font-bold text-center text-black">
                    LEVEL
                  </p>

                  <div className="bg-[#042436] flex-1 flex items-center justify-center">
                    <p className="text-white font-bold">
                      <span className="text-8xl">
                        {Math.floor(chart.constant)}
                      </span>
                      <span className="text-6xl">
                        .
                        {chart.constantSure
                          ? (chart.constant % 1).toFixed(1).slice(2)
                          : "?"}
                      </span>
                    </p>
                  </div>
                </div>
              </div>
            </section>

            <section className="bg-white/80 flex-1 flex flex-col justify-between items-center p-4 gap-4 text-black overflow-hidden">
              <div className="flex flex-col gap-2 items-center w-full overflow-hidden">
                <p className={cn(titleFontSize, "line-clamp-2 text-center")}>
                  {chart.title}
                </p>
                <hr className="w-full" />
                <p className={cn(artistFontSize, "line-clamp-2 text-center")}>
                  {chart.artist}
                </p>
              </div>

              <div className="flex flex-col w-full gap-4 font-helvetica">
                <p className="font-bold text-5xl self-start">
                  SCORE {chart.score.toLocaleString()}
                </p>
                <p className="font-bold text-5xl self-start">
                  RATING {chart.rating?.toFixed(2) || "??.??"}
                </p>
              </div>
            </section>

            <section className="flex justify-evenly">
              {/* Scale x2.5 */}
              {chart.clearMark ? (
                <Img
                  src={staticFile(
                    `/chuni-web/clearmark/${chart.clearMark.toLowerCase()}.png`,
                  )}
                  alt="Clear Mark"
                  className="w-40 h-11.25"
                />
              ) : (
                <div className="w-40 h-11.25 border-2 border-gray-300 bg-gray-200" />
              )}

              <Img
                src={staticFile(
                  `/chuni-web/rankmark/${getRank(chart.score)}.png`,
                )}
                alt="Rank Mark"
                className="w-40 h-11.25"
              />

              {lamp ? (
                <Img
                  src={staticFile(`/chuni-web/lampmark/${lamp}.png`)}
                  alt={`${lamp} Mark`}
                  className="w-40 h-11.25"
                />
              ) : (
                <div className="w-40 h-11.25 border-2 border-gray-300 bg-gray-200" />
              )}
            </section>
          </article>
        </main>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};
