/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/calcRating": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Calculate rating from play data
     * @description Calculates the player rating based on their best 30 and current 20 songs. Returns processed chart data with ratings.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CalcRatingRequest"];
        };
      };
      responses: {
        /** @description Successfully calculated rating */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["RawImageGen"];
          };
        };
        /** @description Invalid input data or version */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Service unavailable - version configuration missing */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/previewNext": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Preview next version rating calculation
     * @description Calculates what the player rating would be in the next version based on all records.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["PreviewNextRequest"];
        };
      };
      responses: {
        /** @description Successfully calculated preview rating */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PreviewNextResponse"];
          };
        };
        /** @description Invalid input data or version */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/imageProxy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Proxy for music images
     * @description Proxies requests for music cover images to internal S3 bucket. Returns the image with appropriate caching headers.
     */
    get: {
      parameters: {
        query: {
          img: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Image returned successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "image/jpeg": string;
            "image/png": string;
          };
        };
        /** @description Invalid image parameter or not an image */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/musicData": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get music data by version
     * @description Retrieve all music data including chart information for a specific game version
     */
    get: {
      parameters: {
        query: {
          /** @description Game version identifier */
          version: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Music data successfully retrieved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["MusicDataView"][];
          };
        };
        /** @description Bad request - invalid or missing version parameter */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user play stats history
     * @description Returns the user's play statistics history including player level, play count, rating, and overpower value at each distinct play session. Requires authentication via API key or session.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User stats successfully retrieved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UserStats"][];
          };
        };
        /** @description Unauthorized - Invalid or missing API key/session */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/forRating": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user rating breakdown with profile
     * @description Returns the user's complete rating data including profile information, best 30 songs, current 20 songs, and calculated rating averages. This endpoint provides all data needed for rating display and image generation. Requires authentication via API key or session.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Rating breakdown with profile successfully retrieved. Includes profile data, best 30 songs (BEST rating type), current 20 songs (CURRENT rating type), and rating averages. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ForRatingResult"];
          };
        };
        /** @description Unauthorized - Invalid or missing API key/session */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Not Found - No rating data found for this user */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/musicRecord": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user music record
     * @description Returns the user's play records for a specific music ID across all difficulties. Requires authentication via API key or session.
     */
    get: {
      parameters: {
        query?: {
          /** @description The music ID to retrieve records for */
          musicId?: number | null;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Music record successfully retrieved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["MusicRecord"];
          };
        };
        /** @description Bad Request - Invalid or missing musicId parameter */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized - Invalid or missing API key/session */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Not Found - Music not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      /** @example Bad Request */
      message: string;
    };
    VersionQuery: {
      /**
       * @description Game version identifier
       * @example XVRS
       * @example VRS
       */
      version: string;
    };
    ChartLevel: {
      level: string;
      constant: number | null;
    };
    Chart: {
      id: number | null;
      title: string;
      /** @enum {string} */
      difficulty: "basic" | "advanced" | "expert" | "master" | "ultima";
      score: number | null;
      /** @enum {string|null} */
      clearMark?:
        | "CLEAR"
        | "HARD"
        | "BRAVE"
        | "ABSOLUTE"
        | "CATASTROPHY"
        | null;
      /** @default false */
      fc: boolean;
      /** @default false */
      aj: boolean;
      /** @default false */
      isHidden: boolean;
    };
    Profile: {
      characterImage: string;
      /** @enum {string} */
      characterRarity:
        | "NORMAL"
        | "BRONZE"
        | "SILVER"
        | "GOLD"
        | "PLATINUM"
        | "RAINBOW"
        | "HOLOGRAPHIC";
      teamName?: string | null;
      /** @enum {string|null} */
      teamEmblem?:
        | "NORMAL"
        | "GREEN"
        | "YELLOW"
        | "RED"
        | "PURPLE"
        | "SILVER"
        | "GOLD"
        | "RAINBOW"
        | null;
      honorText: string;
      /** @enum {string} */
      honorRarity:
        | "NORMAL"
        | "BRONZE"
        | "SILVER"
        | "GOLD"
        | "PLATINUM"
        | "RAINBOW"
        | "HOLOGRAPHIC";
      playerLevel: number | null;
      playerName: string;
      classBand?: number | null;
      classEmblem?: number | null;
      rating: number | null;
      overpowerValue: number | null;
      overpowerPercent: number | null;
      /** Format: date */
      lastPlayed: string | null;
      playCount: number | null;
    };
    HiddenChart: {
      search?: string | null;
      /** @enum {string} */
      difficulty: "basic" | "advanced" | "expert" | "master" | "ultima";
      /** @enum {string} */
      ratingType: "BEST" | "CURRENT" | "SELECTION_BEST" | "SELECTION_CURRENT";
      score: number | null;
      /** @enum {string|null} */
      clearMark?:
        | "CLEAR"
        | "HARD"
        | "BRAVE"
        | "ABSOLUTE"
        | "CATASTROPHY"
        | null;
      /** @default false */
      fc: boolean;
      /** @default false */
      aj: boolean;
    };
    ChartForRender: components["schemas"]["Chart"] & {
      constant: number;
      constantSure: boolean;
      rating: number | null;
      image: string | null;
    };
    RatingDetail: {
      bestAvg: number;
      currentAvg: number;
      totalAvg: number;
    };
    RawImageGen: {
      profile: components["schemas"]["Profile"];
      best: components["schemas"]["ChartForRender"][];
      current: components["schemas"]["ChartForRender"][];
      rating: components["schemas"]["RatingDetail"];
    };
    CalcRatingRequest: {
      data: {
        profile: components["schemas"]["Profile"];
        best: components["schemas"]["Chart"][];
        current: components["schemas"]["Chart"][];
        hidden?: components["schemas"]["HiddenChart"][];
      };
      /** @example XVRS */
      version: string;
    };
    PreviewNextRequest: {
      data: {
        profile: components["schemas"]["Profile"];
        best: components["schemas"]["Chart"][];
        current: components["schemas"]["Chart"][];
        hidden?: components["schemas"]["HiddenChart"][];
        allRecords: components["schemas"]["Chart"][];
      };
      /** @example XVRS */
      version: string;
    };
    PreviewNextResponse: {
      profile: components["schemas"]["Profile"];
      best: components["schemas"]["Chart"][];
      current: components["schemas"]["Chart"][];
    };
    ImageProxyQuery: {
      /** @example jacket_image.png */
      img: string;
    };
    UserStats: {
      /** Format: date */
      lastPlayed: string | null;
      jobId: number;
      playerLevel: number;
      playCount: number;
      rating: string;
      overpowerValue: string;
    };
    ForRatingResult: components["schemas"]["RawImageGen"] & {
      jobId: number;
      /**
       * @example XVRS
       * @example VRS
       */
      version: string;
    };
    MusicInfo: {
      id: number;
      category: string;
      title: string;
      artist: string;
      image: string;
      version: string | null;
    };
    MusicRecordItem: {
      /** @enum {string} */
      difficulty: "basic" | "advanced" | "expert" | "master" | "ultima";
      score: number;
      /** @enum {string|null} */
      clearMark: "CLEAR" | "HARD" | "BRAVE" | "ABSOLUTE" | "CATASTROPHY" | null;
      fc: boolean;
      aj: boolean;
      fullChain: number;
      /** Format: date */
      lastPlayed: string | null;
    };
    MusicRecord: {
      musicInfo: components["schemas"]["MusicInfo"];
      records: {
        basic: components["schemas"]["MusicRecordItem"][];
        advanced: components["schemas"]["MusicRecordItem"][];
        expert: components["schemas"]["MusicRecordItem"][];
        master: components["schemas"]["MusicRecordItem"][];
        ultima: components["schemas"]["MusicRecordItem"][] | null;
      };
    };
    MusicDataView: {
      id: number;
      title: string;
      artist: string;
      image: string;
      releasedVersion: string | null;
      basic?: components["schemas"]["ChartLevel"];
      advanced?: components["schemas"]["ChartLevel"];
      expert?: components["schemas"]["ChartLevel"];
      master?: components["schemas"]["ChartLevel"];
      ultima?: components["schemas"]["ChartLevel"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
