/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/calcRating": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Calculate rating from play data
     * @description Calculates the player rating based on their old/best 35 and new/current 15 songs. Returns processed chart data with ratings. Uses summation instead of average.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CalcRatingRequest"];
        };
      };
      responses: {
        /** @description Successfully calculated rating */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["RawImageGen"];
          };
        };
        /** @description Invalid input data or version */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Service unavailable - version configuration missing */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/previewNext": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Preview next version rating calculation
     * @description Calculates what the player rating would be in the next version based on all records.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["PreviewNextRequest"];
        };
      };
      responses: {
        /** @description Successfully calculated preview rating */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PreviewNextResponse"];
          };
        };
        /** @description Invalid input data or version */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/imageProxy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Proxy for music images
     * @description Proxies requests for music cover images to internal S3 bucket. Returns the image with appropriate caching headers.
     */
    get: {
      parameters: {
        query: {
          img: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Image returned successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "image/jpeg": string;
            "image/png": string;
          };
        };
        /** @description Invalid image parameter or not an image */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/musicData": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get music data by version
     * @description Retrieve all music data including chart information for a specific game version
     */
    get: {
      parameters: {
        query: {
          /** @description Game version identifier */
          version: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Music data successfully retrieved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["MusicDataView"][];
          };
        };
        /** @description Bad request - invalid or missing version parameter */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a new scraping job
     * @description Creates a new job entry in the database to track a scraping session. Returns the job ID and start timestamp. This endpoint is used by the scraper at the beginning of execution. Requires API key authentication.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Job created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CreateJobResponse"];
          };
        };
        /** @description Unauthorized - Invalid or missing API key */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/finish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Finish a scraping job
     * @description Finish a scraping job by adding log (or error message if failed). Requires API key authentication.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json":
            | components["schemas"]["FinishJobSuccess"]
            | components["schemas"]["FinishJobFailure"];
        };
      };
      responses: {
        /** @description Job finished successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["FinishJobResponse"];
          };
        };
        /** @description Bad request - Invalid request body or job ID not found */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized - Invalid or missing API key */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/data": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Save scraping data to database
     * @description Saves all scraped data including player profile, music records, and rating breakdowns to the database. Requires API key authentication.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["SaveJobDataRequest"];
        };
      };
      responses: {
        /** @description Data saved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SaveJobDataResponse"];
          };
        };
        /** @description Bad request - Invalid request body, job not found, or job doesn't belong to user */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized - Invalid or missing API key */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user play stats history
     * @description Returns the user's play statistics history including play count (current and total), rating, and star count at each distinct play session. Requires authentication via API key or session.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User stats successfully retrieved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UserStats"][];
          };
        };
        /** @description Unauthorized - Invalid or missing API key/session */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/forRating": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user rating data for image generation
     * @description Returns the user's profile, best 35 songs, and current 15 songs with rating details for the latest job. This endpoint provides all data needed for rating card/image generation. Requires authentication via API key or session.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Rating data successfully retrieved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ForRatingResult"];
          };
        };
        /** @description Unauthorized - Invalid or missing API key/session */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description No rating data found for this user */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/musicRecord": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user music record
     * @description Returns the user's play records for a specific music title across all chart types and difficulties. Requires authentication via API key or session.
     */
    get: {
      parameters: {
        query: {
          /** @description The music title to retrieve records for */
          musicTitle: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Music record successfully retrieved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["MusicRecord"];
          };
        };
        /** @description Bad Request - Invalid or missing musicTitle parameter */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized - Invalid or missing API key/session */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Not Found - Music not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/playCount": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get play count since various time periods
     * @description Returns the number of plays since today (7AM JST), this week (Monday 7AM JST), this month (1st day 7AM JST), last 30 days, last 365 days, and play count for the current version.
     *
     *     The 'thisVersion' field returns playCountCurrent from the latest row. If currentPlayCount parameter is provided, it applies an offset: playCountCurrent + (currentPlayCount - playCountTotal).
     *
     *     Requires authentication via API key or session.
     */
    get: {
      parameters: {
        query?: {
          /** @description Optional current play count to use for calculation. If not provided, the latest play count from the database will be used. */
          currentPlayCount?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Play count statistics successfully retrieved. Returns the number of plays since various time periods. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PlayCountSince"];
          };
        };
        /** @description Bad Request - Invalid currentPlayCount parameter (must be a non-negative integer) */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized - Invalid or missing API key/session */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      /** @example Bad Request */
      message: string;
    };
    VersionQuery: {
      /**
       * @description Game version identifier
       * @example CiRCLE
       */
      version: string;
    };
    ChartLevel: {
      level: string;
      constant: number | null;
    };
    ImageProxyQuery: {
      /** @example jacket_image.png */
      img: string;
    };
    CreateJobResponse: {
      /**
       * @description The unique identifier for the created job
       * @example 12345
       */
      jobId: number;
      /**
       * Format: date-time
       * @description The timestamp when the job was created (ISO 8601 format)
       * @example 2026-01-10T12:00:00.000Z
       */
      jobStart: string;
    };
    FinishJobSuccess: {
      /**
       * @description The ID of the job to finish
       * @example 12345
       */
      jobId: number;
      /**
       * @description Status discriminator for successful job completion (enum property replaced by openapi-typescript)
       * @enum {string}
       */
      status: "success";
      /**
       * @description Execution logs from the job
       * @example Step 1: Login completed
       *     Step 2: Data fetched successfully
       */
      jobLog: string;
    };
    FinishJobFailure: {
      /**
       * @description The ID of the job to finish
       * @example 12345
       */
      jobId: number;
      /**
       * @description Status discriminator for failed job completion (enum property replaced by openapi-typescript)
       * @enum {string}
       */
      status: "failure";
      /**
       * @description Error message or stack trace from the failed job
       * @example Error: Failed to connect to database
       */
      jobError: string;
      /**
       * @description Execution logs from the job (if any were captured)
       * @example Step 1: Login completed
       *     Step 2: Connection failed
       */
      jobLog?: string;
    };
    FinishJobResponse: {
      /**
       * @description Whether the job was successfully marked as finished
       * @example true
       */
      success: boolean;
      /**
       * @description Confirmation message
       * @example Job 12345 finished successfully
       */
      message: string;
    };
    SavePlayerData: {
      characterImage: string;
      honorText: string;
      /** @enum {string} */
      honorRarity: "NORMAL" | "BRONZE" | "SILVER" | "GOLD" | "RAINBOW";
      playerName: string;
      courseRank: number;
      classRank: number;
      rating: number;
      star: number;
      playCountCurrent: number;
      playCountTotal: number;
      /**
       * Format: date-time
       * @description Last played timestamp (ISO 8601 format)
       * @example 2026-01-10T12:00:00.000Z
       */
      lastPlayed: string;
    };
    SaveRatingRecords: {
      /** @description Old (Best) 35 songs for rating */
      best: components["schemas"]["Chart"][];
      /** @description New (Current) 15 songs for rating */
      current: components["schemas"]["Chart"][];
      /** @description Selection old candidates */
      selectionBest: components["schemas"]["Chart"][];
      /** @description Selection new candidates */
      selectionCurrent: components["schemas"]["Chart"][];
      /** @description All play records */
      allRecords: components["schemas"]["Chart"][];
      history?: components["schemas"]["HistoryRecord"][];
    };
    Chart: {
      title: string;
      /** @enum {string} */
      chartType: "std" | "dx";
      /** @enum {string} */
      difficulty: "basic" | "advanced" | "expert" | "master" | "remaster";
      score: number;
      dxScore?: number | null;
      dxScoreMax?: number | null;
      /** @enum {string|null} */
      comboMark?: "NONE" | "FC" | "FC+" | "AP" | "AP+" | null;
      /** @enum {string|null} */
      syncMark?: "NONE" | "SYNC" | "FS" | "FS+" | "FDX" | "FDX+" | null;
    };
    HistoryRecord: {
      title: string;
      dxScore?: number | null;
      dxScoreMax?: number | null;
      /** @enum {string|null} */
      comboMark?: "NONE" | "FC" | "FC+" | "AP" | "AP+" | null;
      /** @enum {string|null} */
      syncMark?: "NONE" | "SYNC" | "FS" | "FS+" | "FDX" | "FDX+" | null;
      score: number;
      /** @enum {string} */
      chartType: "std" | "dx" | "utage" | "utage-buddy";
      /** @enum {string} */
      difficulty:
        | "basic"
        | "advanced"
        | "expert"
        | "master"
        | "remaster"
        | "utage";
      trackNo: number;
      /** Format: date-time */
      playedAt: string;
    };
    SaveJobDataRequest: {
      /**
       * @description The ID of the job to save data for
       * @example 12345
       */
      jobId: number;
      playerData: components["schemas"]["SavePlayerData"] & unknown;
      recordData: components["schemas"]["SaveRatingRecords"] & unknown;
      /** @description Raw HTML from player data page (for debugging) */
      playerDataHtml: string;
      /** @description Raw HTML from music record pages (for debugging) */
      allMusicRecordHtml: string;
      imgGenInput: components["schemas"]["ImgGenInput"];
      /**
       * @description Calculated rating from image generation service
       * @example 15420
       */
      calculatedRating?: number;
      /**
       * @description Game version
       * @example CiRCLE
       */
      version: string;
    };
    /** @description Data formatted for image generation */
    ImgGenInput: {
      profile: components["schemas"]["Profile"];
      best: components["schemas"]["Chart"][];
      current: components["schemas"]["Chart"][];
      scraperVersion?: string;
    };
    Profile: components["schemas"]["ProfileWithoutLastPlayed"] & {
      /** Format: date-time */
      lastPlayed: string;
    };
    ProfileWithoutLastPlayed: {
      characterImage: string;
      honorText: string;
      /** @enum {string} */
      honorRarity: "NORMAL" | "BRONZE" | "SILVER" | "GOLD" | "RAINBOW";
      playerName: string;
      courseRank?: number;
      classRank?: number;
      rating: number;
      star: number;
      playCountCurrent?: number;
      playCountTotal?: number;
    };
    SaveJobDataResponse: {
      /**
       * @description Whether the data was successfully saved
       * @example true
       */
      success: boolean;
      /**
       * @description Confirmation message
       * @example Job data saved successfully
       */
      message: string;
      /**
       * @description Number of music records inserted
       * @example 450
       */
      recordsInserted: number;
    };
    ChartForRender: components["schemas"]["Chart"] & {
      level: number;
      levelSure: boolean;
      rating: number | null;
      image: string | null;
    };
    RatingDetail: {
      /**
       * @description Sum of best 35 songs rating
       * @example 14520
       */
      bestSum: number;
      /**
       * @description Sum of current 15 songs rating
       * @example 6230
       */
      currentSum: number;
      /**
       * @description Total rating (bestSum + currentSum)
       * @example 20750
       */
      total: number;
    };
    RawImageGen: {
      profile: components["schemas"]["Profile"];
      /** @description Best 35 songs with rating info */
      best: components["schemas"]["ChartForRender"][];
      /** @description Current 15 songs with rating info */
      current: components["schemas"]["ChartForRender"][];
      rating: components["schemas"]["RatingDetail"];
    };
    CalcRatingRequest: {
      data: components["schemas"]["ImgGenInput"];
      /** @example CiRCLE */
      version: string;
    };
    PreviewNextRequest: {
      data: components["schemas"]["FullPlayDataInput"];
      /** @example CiRCLE */
      version: string;
    };
    FullPlayDataInput: components["schemas"]["ImgGenInput"] & {
      allRecords: components["schemas"]["Chart"][];
      history: components["schemas"]["HistoryRecord"][];
    };
    PreviewNextResponse: {
      profile: components["schemas"]["Profile"];
      best: components["schemas"]["Chart"][];
      current: components["schemas"]["Chart"][];
    };
    UserStats: {
      /** Format: date-time */
      lastPlayed: string | null;
      jobId: number;
      playCountCurrent: number;
      playCountTotal: number;
      rating: number;
      star: number;
    };
    ForRatingResult: components["schemas"]["RawImageGen"] & {
      jobId: number;
      /**
       * @example FESTiVAL PLUS
       * @example BUDDiES
       */
      version: string;
    };
    MusicDataView: {
      title: string;
      artist: string;
      image: string;
      /** @enum {string} */
      chartType: "std" | "dx";
      /** Format: date */
      releaseDate: string;
      /** @example CiRCLE */
      releasedVersion: string;
      releasedVersionIntl?: string;
      basic?: components["schemas"]["ChartLevel"];
      advanced?: components["schemas"]["ChartLevel"];
      expert?: components["schemas"]["ChartLevel"];
      master?: components["schemas"]["ChartLevel"];
      remaster?: components["schemas"]["ChartLevel"];
    };
    MusicRecord: {
      musicInfo: components["schemas"]["MusicInfo"];
      records: components["schemas"]["MusicRecordItem"][];
    };
    MusicInfo: {
      title: string;
      category: string;
      artist: string;
      image: string;
      version: number;
    };
    MusicRecordItem: {
      /** @enum {string} */
      chartType: "std" | "dx";
      /** @enum {string} */
      difficulty: "basic" | "advanced" | "expert" | "master" | "remaster";
      score: number;
      dxScore: number;
      dxScoreMax: number;
      /** @enum {string} */
      comboMark: "NONE" | "FC" | "FC+" | "AP" | "AP+";
      /** @enum {string} */
      syncMark: "NONE" | "SYNC" | "FS" | "FS+" | "FDX" | "FDX+";
      /** Format: date-time */
      lastPlayed: string | null;
    };
    PlayCountSince: {
      today?: number;
      thisWeek?: number;
      thisMonth?: number;
      last30Days?: number;
      last365Days?: number;
      thisVersion?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
